apiVersion: apps/v1
kind: Deployment
metadata:
 name: newmoviesapi
 labels:
    app: newmoviesapi
spec:
 replicas: 2
 selector:
    matchLabels:
      app: newmoviesapi
 template:
    metadata:
       labels:
        app: newmoviesapi
    spec:
      containers:
      - name: newmoviesapiservice
        image: us.icr.io/ibmperumf2/newmoviesapiimg
        ports:
        - containerPort: 80        
---
apiVersion: v1
kind: Service
metadata:
 name: newmoviesapi
spec:
 type: NodePort
 selector:
   app: newmoviesapi
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32075
 selector:
   app: newmoviesapi